version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./backend:/usr/src
    tty: true
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    tty: true
    volumes:
      - ./frontend/my-app:/app
    command: sh -c "npm run dev"
networks:
  app-network:
    driver: bridge
